### ISSUE TITLE
[Feature request] Use a better initial directory when saving a new file

### ISSUE THREAD

**Issue by ReFreezed** [juzzlin/Heimer#100]
When saving a new file, the "save as" dialog currently shows the home directory. It should instead either:
- if an existing file is open, show the directory of that file.
- show the last directory that a file was saved in (or remember the last directory any of the Open or Save dialogs showed).

**Comment by juzzlin** [comment]
Implemented in dbbec5a3334733e5ce23f9a55a5e7d45caa75744. Thanks for reporting!
