### ISSUE TITLE
Heimer works in linux under Chrome OS

### ISSUE THREAD

**Issue by Yohannas** [juzzlin/Heimer#104]
Heimer saves mindmaps in /usr/.....
and exports under /proc/...

but displays home and userspace in files screen

IMHO it does not do anything with what you select there it saves in splaces as mentioned before.

BTW. A wonderfull straitforward mindmapping programme, i like it

**Comment by juzzlin** [comment]
I guess this issue can be closed now? :)

**Comment by Yohannas** [comment]
Yes
