### ISSUE TITLE
Memory leak when changing Edge width, Text size and corner radius

### ISSUE THREAD

**Issue by Exidak** [juzzlin/Heimer#106]
I saw that application consumes more memory when changing values by arrows too often (after 1 minute of changing from 14 to 58 Mb)

**Comment by juzzlin** [comment]
How often? That could just be the undo stack taking more memory, not a leak as such.

**Comment by Exidak** [comment]
about 3 times a second.
I think that's really undo stack, but it's not ok X3 memory usage. Maybe refactor undo/redo mechanics? Not save copy of ALL parameters but zipping them or save only changed values?

**Comment by juzzlin** [comment]
Let's try this: be3b43ba78c3819a27eb2058a1a253411a112728

I made it to not push every single quick change (< 500 ms) to the undo stack. There are also some other possibilities to improve this (change sets, write to disk etc), but they'd need a lot of more work to implement.
