### ISSUE TITLE
package required for MX Linux

### ISSUE THREAD

**Issue by pannet1** [juzzlin/Heimer#107]
can you please make a package for mxlinux. since, mx linux does not use systemctl cannot use snap and hence this request

**Comment by SwampRabbit** [comment]
Just some clarification first, MX Linux can run the snap package, but a user needs to boot with systemd.
It is just not our default, but both sysvinit and systemd are supported.

Heimer looks to have everything needed or documented to package it for the repos already, I don't think @juzzlin needs to do anything at this point until we can verify that it cannot be built properly for the repos.

The MX packaging team will take a look at it though.

**Comment by SwampRabbit** [comment]
This issue can be closed, Heimer has been added to the MX Linux repository, I will sponsor this package moving forward.

@juzzlin if you would like I can provide the debianization files, it may help other Debian or Ubuntu based distros to start populating it in their repos as well.

**Comment by juzzlin** [comment]
Yeah, I could probably add them as an example. Currently the Debian packages in releases are built with CPack so it's not a real debianization (yet handy).

**Comment by SwampRabbit** [comment]
> Yeah, I could probably add them as an example. Currently the Debian packages in releases are built with CPack so it's not a real debianization (yet handy).

Ok, I will drop them on here as soon as I can swing some time  :)
It is a very nice and snappy application, I am glad we had a user request it.

CPack is great and all, but proper reproducible source builds are needed for repos.
It was easy to debianize Heimer, you had everything documented or in old commits.

**Comment by pannet1** [comment]
Hope Heimer receives the attention it deserves after getting into MX Linux repository.  I have not even used it once but there is   a great youtube video demonstrating its simplicity.

Thanks for the support @SwampRabbit and @juzzlin for Heimer.
