### ISSUE TITLE
[Feature Request] Make default direction of arrows configurable

### ISSUE THREAD

**Issue by carfesh** [juzzlin/Heimer#109]
When a new node is created below an existing node, I'd like the arrow to not have a direction, but just be a straight line. That way Heimer could be used very well as a non-hierarchical clustering/brainstorming tool. Currently, I have to remove the arrow from every line by right-clicking. 

Besides that, I like the simpleness of Heimer, thanks for this great tool!

**Comment by juzzlin** [comment]
I'm planning to add a separate settings menu that would include some user defaults. This could be one of them. Thanks for reporting!

**Comment by juzzlin** [comment]
Fixed in 9997651262cc57afd24f0349275f9e433ddc9388. Thanks for reporting!
