### ISSUE TITLE
[Feedback] First use

### ISSUE THREAD

**Issue by xuijuthub** [juzzlin/Heimer#116]
Hi.
Giving (hopefully) constructive feedback on first use.
- Unconvenient in case: Ctrl+Z does not work when text input is on. This behavior happened when accidentally created new entity and wanted to rollback.
- Not very apparent: how to select lines, with time object selection happens to be rmb, lmb for moving and creating. Adding simple how to use/controls chapter in readme would come useful.
- Did not figure out how to create a line between two entities.

Looking forward to future development!:)

**Comment by juzzlin** [comment]
Some explanation:

- Ctrl+Z does not work because unfortunately the text field has its own built-in undo mechanism
- I agree that some selections are now a bit confusing. I might improve the logic a bit.
- You can create a line/edge just by dragging the "+" icon on top of some other object :)

Thanks!

**Comment by xuijuthub** [comment]
>Ctrl+Z does not work because unfortunately the text field has its own built-in undo mechanism

- Possibly the mechanism could be initialized once actually inputing text. And it also should look out for text in clipboard and if that is so, initialize it on CTRL+V.

>You can create a line/edge just by dragging the node creation "handle" of object A on top of some other object B :)

Oh! :) 

- It should also be able to override direction of already linked object.
- And might be better to have additional icon for adding the edges (the same way there are two buttons one for text colour, another for entity background).
- Selecting object and hitting delete key does not delete the object.

Noticed nothing more. Thanks.

**Comment by juzzlin** [comment]
You can change the direction of an edge by right-clicking on it and
selecting the edge style. Is this what you were looking for?

**Comment by juzzlin** [comment]
I will consider your suggestions to improve Heimer. Thanks! :)

**Comment by xuijuthub** [comment]
>You can change the direction of an edge by right-clicking on it and
selecting the edge style. Is this what you were looking for?

Sorry for not being clear, I meant drag-and-drop should be able to override the direction.

Cheers! :)

**Comment by juzzlin** [comment]
> > You can change the direction of an edge by right-clicking on it and
> > selecting the edge style. Is this what you were looking for?
> 
> Sorry for not being clear, I meant drag-and-drop should be able to override the direction.
> 
> Cheers! :)

Oh, right. Seems that it's not in Settings => Defaults. Need to fix that :)

**Comment by juzzlin** [comment]
See https://github.com/juzzlin/Heimer/issues/118

**Comment by juzzlin** [comment]
See #117
