### ISSUE TITLE
Add Debian 9 package

### ISSUE THREAD

**Issue by Symbian9** [juzzlin/Heimer#13]
Please, add also `.deb` for Debian 9.x

- https://github.com/juzzlin/Heimer/releases/tag/1.0.0

**Comment by juzzlin** [comment]
Ubuntu is based on Debian so I don't see much risk using that .deb :) Almost only thing that matters is the glibc version. AFAIK Ubuntu 16.04 is older that Debian 9 so there shouldn't be any problems. Maybe I'll rename those packages.

I will take a look at AppImage after I have automated Snap builds. Thanks!
