### ISSUE TITLE
Heimer does not accept dead keys for accented characters

### ISSUE THREAD

**Issue by thadeupenna** [juzzlin/Heimer#131]
When I try to type accented characters as áéáãà, Heimer prints it without the accent. However, if I type the sentence outside the Heimer, in a terminal, for example, and copy and paste it, the sentence is correctly displayed. All other qt applications I have installed are playing nicely with accents.

**Comment by juzzlin** [comment]
Heimer uses `QGraphicsTextItem` for text input and I don't think it's widely used by other Qt applications. 

Hmm...now that I tested it seems that I can type at least á, à, è, é without problems. Built from master and running on Ubuntu 20.04 LTS / Qt 5.12.8.

**Comment by thadeupenna** [comment]
I confirm it is working with the new version in Ubuntu 20.04. I was using a snap package that I removed and install the official version from here. Thanks and I apologize for the inconvenience. I am closing the bug report.
