### ISSUE TITLE
Question - App name and file extension

### ISSUE THREAD

**Issue by rmszc81** [juzzlin/Heimer#136]
Hello @juzzlin,

Just wondering about the name and file extension... Heimer... Alz... Alzheimer? 🤔

Btw, is there any plans for freebsd port?

Thank you.

**Comment by juzzlin** [comment]
Yeah, it's an intended joke :p

I have no plans for a FreeBSD port because I don't use it myself, but nothing prevents someone from doing that. The code shouldn't need any modifications - just build on FreeBSD. I have no idea about packaging on FreeBSD, though.

**Comment by rmszc81** [comment]
Thanks for the info @juzzlin,

BTW, some nice person already added Heimer as a FreeBSD port, as you can see it here https://www.freshports.org/graphics/heimer/

Please take a look in the screenshot below, it's Heimer running on FreeBSD 12.2

![image](https://user-images.githubusercontent.com/11450286/105746959-b86d1880-5f72-11eb-8d07-1a22a51f4639.png)

Thanks for such great tool buddy. You can close the ticket now, :)

**Comment by juzzlin** [comment]
Ok, that's very nice to hear, thanks! 😊
