### ISSUE TITLE
Make it possible to change the font

### ISSUE THREAD

**Issue by raffaelmiribung** [juzzlin/Heimer#138]
It would be lovely to use different fonts than the standard one.

Further, it would be immensely helpful to be able to format text. Perhaps st like `<b>bold</b>`, `<i>italic</i>`, `<li>o item</li>`

<hr>
<b>Headline</b>

Lorem ipsum dolor sit.

_equituur sunt_
<hr>

**Comment by juzzlin** [comment]
Yes, I agree.

**Comment by juzzlin** [comment]
Implemented in 5ccaf0370b2ee9ca3b8746365f23e2e5d348b908.
