### ISSUE TITLE
[Bug] Inexact node selection

### ISSUE THREAD

**Issue by l3td33r** [juzzlin/Heimer#143]
Sometimes if we want to click a node we can't, and the opposite.

I have noticed at least three cases:
- [ ] If we have nodes under each other and want to select the bottom node, the top node gets selected due to some invisible border (even if the mouse cursor is hovering over the top part of the bottom node).
- [ ] Multiselection doesn't select nodes even if all visible parts of them are inside the selection rectangle. To select them we need to select way higher than the visible parts. Should work even if only a small part of the node is inside.
- [x] When connecting edges to nodes, the connection works only if we hover over the bottom-middle part of the node we're connecting to.

**Comment by juzzlin** [comment]
Thanks for reporting!

Some of those issues happen because the "node handles" are not individual objects in the scene. Should be changed this way.

**Comment by juzzlin** [comment]
Connecting nodes by dragging made easier in e08c65381f2dd2d22499b5f2e426c7ddc4ca21ab.

**Comment by l3td33r** [comment]
Nice, thank you for your work!

But a new problem appeared - it's harder to create new children nodes - because they connect with the adjacent nodes, instead of creating a new one. For example it is not possible to create the children node in the middle of these:

![2021-03-13_14-14-21](https://user-images.githubusercontent.com/75885440/111031269-e618fe80-8406-11eb-8a11-9ef3e2d7fda6.png)


> Some of those issues happen because the "node handles" are not individual objects in the scene. Should be changed this way.

Guess that's the way then :P and then calculating the correct overlap score using the proper node positions

**Comment by juzzlin** [comment]
I got this almost implemented - just run into some unexpected problems (who would have guessed!) :)

**Comment by juzzlin** [comment]
Fixed in b8a177a99eba774092a71e1e6218dec0d8d28b87. 

There shouldn't be anymore issues with invisible borders.

**Comment by l3td33r** [comment]
Yup! Selection works better now, except I have noticed one issue - when connecting the node to another, it connects even if we hover with mouse cursor outside the area of the node we're connecting to.
It's as if the node was 2x bigger in size than it is, but only from bottom and the sides. Top works correctly.

+ Not sure if selection rect should also select nodes if only small parts of them are inside the rect? That would be more intuitive I think.

**Comment by juzzlin** [comment]
It connects if the semi-transparent drag node touches the target node. It has always been like this but the threshold was different so it allowed more overlap. Maybe it should be based on cursor position only..

I also noticed some small problems later so I need to fine tune this still a bit ☺️
