### ISSUE TITLE
[Bug] Instant node creation not aligned with the grid

### ISSUE THREAD

**Issue by l3td33r** [juzzlin/Heimer#148]
The node is created exactly at the click point, while it should snap itself to the nearest/rounded grid cell.

Happens when we create node using Ctrl + Shift + F or double-click.

**Comment by juzzlin** [comment]
Thanks for reporting! Noticed this also myself.

**Comment by juzzlin** [comment]
Fixed in e6fc5d84aa47c8f6686a5d6837fbbe32b133dd81. Thanks for reporting!
