### ISSUE TITLE
[Enhancement] Default custom colors

### ISSUE THREAD

**Issue by l3td33r** [juzzlin/Heimer#151]
Set the default 16 colors in the color picker to some predefined values (right now they're all white), to make the workflow easier.

We can use colors from one of the popular palettes:
https://lospec.com/palette-list/island-joy-16 (I like this one, the colors are not too intense)
or https://lospec.com/palette-list/sweetie-16

Related: https://doc.qt.io/qt-5/qcolordialog.html#setCustomColor

**Comment by cantalisa** [comment]
I agree! I think it's a good idea.

Even an option (a toolbar or a button with an ink-bottle icon or something) with default set of colors would be great (or create another one). So in one click you choose if you want it with white nodes and gray background, x-color nodes or y-color background, or so on.

Currently the toolbar is good but the selection of colors somewhat confusing (as for custom colors) and the basic colors are somewhat strong.

**Comment by juzzlin** [comment]
Ok, as seems to be doable with QColorDialog.

**Comment by juzzlin** [comment]
Seems that for example Ubuntu 20.04 shows a different and more simple color dialog than other systems. The system color dialog can be disabled, but not sure if that's an improvement.

**Comment by juzzlin** [comment]
This is the color picker Heimer shows on Ubuntu 20.04 by default:  
![UbuntuPicker](https://user-images.githubusercontent.com/2587783/113612381-6faf9b00-9658-11eb-89ae-597a58cdccda.png)

**Comment by juzzlin** [comment]
This is the Qt (I think!) color picker with custom palette:
![QtPicker](https://user-images.githubusercontent.com/2587783/113612564-af768280-9658-11eb-804a-906e34e37169.png)

**Comment by juzzlin** [comment]
Fixed in 6eb4ca235e20840bafabbd6f88ef2d2286e56380. This can be now more easily further improved. Thanks!

**Comment by l3td33r** [comment]
Wow, looks cool, thanks!
