### ISSUE TITLE
[Enhancement] Do not deselect nodes on screen click

### ISSUE THREAD

**Issue by l3td33r** [juzzlin/Heimer#154]
If we select some nodes and then click on screen to drag the map (or just click without dragging), the nodes get deselected, which makes it difficult to move them over long distances.

**Comment by juzzlin** [comment]
It's annoying - I agree.

**Comment by juzzlin** [comment]
I tried to quickly change the behavior, but this is a bit problematic due to the rubber band initialization and clearing.

**Comment by juzzlin** [comment]
Fixed in 946656b6ed9b1173f290ce263f4037d0ddd6d333. Thanks!
