### ISSUE TITLE
Flatpak

### ISSUE THREAD

**Issue by qwerty287** [juzzlin/Heimer#158]
Hello,
it would be nice if you would provide a Flatpak package on Flathub.
Thanks!

**Comment by juzzlin** [comment]
The biggest problem in these universal package formats seems to be that there are too many of them. Someone else is free to provide Flatpak for Heimer, unfortunately I don't have time to create or maintain it :(

**Comment by PranavBhattarai** [comment]
I want this app to come in Flatpak so that I can install it on Fedora. I wanted to try this software which seems cool.

This looks discouraging.

**Comment by juzzlin** [comment]
> I want this app to come in Flatpak so that I can install it on Fedora. I wanted to try this software which seems cool.
> 
> This looks discouraging.

Did you try the `AppImage` build? That **should** work also on Fedora.

https://github.com/juzzlin/Heimer/releases/download/3.0.0/Heimer-3.0.0-x86_64.AppImage

**Comment by PranavBhattarai** [comment]
That's what I am using for now.
Problem is, it doesn't tell you there is a new update available if there is one, does it?

**Comment by juzzlin** [comment]
> That's what I am using for now. Problem is, it doesn't tell you there is a new update available if there is one, does it?

No, it doesn't, but that could be a useful feature to add :)

**Comment by PranavBhattarai** [comment]
Yes indeed. Please do that.
