### ISSUE TITLE
Letter Colour Distortion

### ISSUE THREAD

**Issue by Dev5H0** [juzzlin/Heimer#169]
Some letters like "l" and "i" next to each other get distorted as you zoom in/out.

Of note:
- It gets more visible the more "affected" letters there are.
- Affects Windows version (I only checked 2.6.0).
- Does not affect Linux version (Heimer 2.6.0) (Not sure if the distro or KDE can affect it, but I'm using Mint Cinnamon rn).

I have a possible solution, which would be adding a slight margin to affected (if not [**ALL**](https://i.gyazo.com/3a35b9a0eae542a47d1d6eed49149179.png)) letters.

I have a [video example](https://i.gyazo.com/8e756f3a79db07c7a11542d703c1326f.mp4), though it's **much** less visible.

**Comment by juzzlin** [comment]
This is a Qt bug, isn't it? I'm not sure how to modify the text rendering like that as I'm just using `QGraphicsTextItem`.

**Comment by Dev5H0** [comment]
Ah, sorry for the incredibly late reply. 

I can't really say, have no proper knowledge of QT, but that might very well be the case, if that's the widget toolkit you use. 

Anyways, I just wanted to report to you about this, as it didn't seem like it was supposed to happen. 😅

**Comment by Dev5H0** [comment]
I'd definitely be up for being able to change the font in general, so you should definitely see if that works, when you have the time.

**Comment by juzzlin** [comment]
Yes, I'm planning to do that next.

**Comment by juzzlin** [comment]
See https://github.com/juzzlin/Heimer/issues/138

**Comment by juzzlin** [comment]
I will close this as one can now work around this by changing the font.
