### ISSUE TITLE
Being able to paste and create a node right-away

### ISSUE THREAD

**Issue by mmahmoudian** [juzzlin/Heimer#173]
This is to some extent an extension to #51. The idea is that it would be great if user can paste something from clipboard (e.g text, image) and Heimer automatically create a floating node for it. This saves lots of time especially when the idea is to inset figures into the mix as user can take a screenshot or pipe something from imagemagic and then paste it straight into Heimer.

Just to provide some context, I work with statistical tools (mainly R) and I'm producing lots of plots and the plots can easily explain a lot of information condensed into one figure. Alternatively when I'm reading a research article, it is beneficial to draw what they have done and usually at every major step there is a figure and I can directly use that as a node in Heimer. At the moment I use LibreOffice Draw, but it is not ideal as I have to spend time arranging arrows and etc.

**Comment by juzzlin** [comment]
I like the idea, yes.

**Comment by juzzlin** [comment]
Creating a new node from copied text is now (intially) implemented in 671a558913922782b02a4e6a06d953cc814d48a1. Thanks for suggesting this!

**Comment by mmahmoudian** [comment]
@juzzlin my main motive for opening this feature request was to create a node by pasting an image from clipboard this is very handy when dealing with screenshots.

**Comment by juzzlin** [comment]
I didn't test this that extensively (just pasted image from Gimp for now), but some kind of an image pasting feature is now implemented in b196336297173bb88216be7347392f079a0d2a59.
