### ISSUE TITLE
Icon is installed in /usr/share/icons/hicolor/64x64 but actual size is 256x256

### ISSUE THREAD

**Issue by fpesari** [juzzlin/Heimer#186]
Hello,

I think [this](https://raw.githubusercontent.com/juzzlin/Heimer/master/data/icons/heimer.png) is the file which gets copied to `/usr/share/icons/hicolor/64x64` but its size is 256x256, so it should be copied in `/usr/share/icons/hicolor/256x256` instead. Thanks!

**Comment by juzzlin** [comment]
Fixed in a58a581b732af048c709019d268c2ba628d95920. Thanks for reporting!
