### ISSUE TITLE
Better arrow control for text, toggleable shadows & more colour customisation. 

### ISSUE THREAD

**Issue by Dev5H0** [juzzlin/Heimer#197]
When you're in the middle of the bottom line of a text box, pressing the down arrow send you to the end of the arrow, and reverse for the top line.

And please make it possible to toggle shadows, and edit the colour of nodes, shadows, text, and the inside of text boxes.

**Comment by juzzlin** [comment]
Some global settings for shadows: https://github.com/juzzlin/Heimer/issues/210
