### ISSUE TITLE
Fit-to-Screen-Shortcut

### ISSUE THREAD

**Issue by mmeinesz** [juzzlin/Heimer#199]
Hi, this is your sponsor from 2021 December, I warned you I will have some requests ;-)
The shortcut "zoom to fit" is "ctrl o".
In my environment (ubuntu 18.04) it opens the "open file" dialog inside Heimer. It does not seem to be overwritten by the system itself but seems an internal Heimer issue.

I googled a bit and a common shortcut for fit to 100% is often "ctrl alt f". Some use also "ctrl 0" if I am not mistaken.

Cheers, Moritz

**Comment by juzzlin** [comment]
Hmm...are you sure that it's not Ctrl+0 (zero) ? I need to check that later, but in the Windows version I'm right now using the shortcut is Ctrl+0. That's what it already should be also in the Ubuntu version.

**Comment by mmeinesz** [comment]
you are right, it is ctrl 0 ("zerro"). "0" and "O" look similar - my mistake.

**Comment by juzzlin** [comment]
No problem, I'll close this then :)
