### ISSUE TITLE
Click dragging from an existing node, then pressing delete before dropping the node, crashes the program

### ISSUE THREAD

**Issue by big-smitty** [juzzlin/Heimer#205]
Steps to reproduce:
If you click an existing node, then drag to make a new node, but try to delete the new node before actually dropping it, the entire program crashes. 

Expected Behavior:
no crashing, the new node should be deleted

Build: 3.2.0 Win 10

**Comment by juzzlin** [comment]
Thanks for reporting!

**Comment by juzzlin** [comment]
Fixed in 5c3814104ba0626fb1d5e98dcb0eb47b3726b104.
