### ISSUE TITLE
An option to change the size of the arrows

### ISSUE THREAD

**Issue by big-smitty** [juzzlin/Heimer#206]
The arrows are very small and it makes it difficult to see what direction they are facing, especially on low resolutions or larger maps.
An option to increase the size/thickness of the arrows would be a big QOL increase.

**Comment by juzzlin** [comment]
Setting the edge/arrow width is already possible in the bottom toolbar. It won't make the L and R arrow lines longer, though.

**Comment by big-smitty** [comment]
That might be a good fix, I think. Having the arrowheads be wider and more noticeable, or at least configurable.
Even looking at this small example is confusing, with the biggest edges allowed:
![image](https://user-images.githubusercontent.com/85451361/165037811-fa6a7e10-0446-4fc2-92a8-a6e7793233f9.png)

The color dots that show on the edges when you're selecting their parent might be a good fix as well, having the arrowheads be colored could make things easy to read from a distance.
Just an idea, thanks for your work on this awesome program :)

**Comment by juzzlin** [comment]
Thanks for your input. I will definitely fix this.

**Comment by juzzlin** [comment]
Option to set arrow size implemented in c6f68a2cd8fdba020610b7545568c74e054c3dee
