### ISSUE TITLE
FreeBSD: CMake unknown system FreeBSD !

### ISSUE THREAD

**Issue by nunotexbsd** [juzzlin/Heimer#209]
Hello,

I'm heimer FreeBSD port maintainer and I updated it to latest version without any issues and program runs ok.

After investigating build logs I found:

`-- Detecting CXX compile features - done
-- Linux/Unix build with system install targets.
CMake Warning at src/contrib/range-v3-0.11.0/cmake/ranges_env.cmake:50 (message):
  [range-v3 warning]: unknown system FreeBSD !
Call Stack (most recent call first):
  src/contrib/range-v3-0.11.0/CMakeLists.txt:50 (include)`

Is there a posssibility of including FreeBSD in upstream config/code?

Thanks,

**Comment by juzzlin** [comment]
Seems that the warning comes from this range v3 library we added some time ago. It's a library that implements some C++20 features so if Heimer builds and runs ok this shouldn't matter. Otherwise I'll fix it somehow.

**Comment by nunotexbsd** [comment]
It runs ok without any issues.

Thanks,

Nuno Teixeira
