### ISSUE TITLE
Release source tarball

### ISSUE THREAD

**Issue by nunotexbsd** [juzzlin/Heimer#213]
Hello,

Could this project provide a release source tarball, e.g, [heimer-3.4.0.tar.gz](https://github.com/juzzlin/Heimer/releases/download/3.4.0/heimer-3.4.0.tar.gz) to be included toguether with Release Assets?

This have the advantage to download source code from a fixed tarball instead of an auto-generated one: https://github.com/juzzlin/Heimer/archive/refs/tags/3.4.0.tar.gz.

Since I'm maintaining FreeBSD Heimer [port](https://www.freshports.org/graphics/heimer/), instead of using github account name/project to get auto-generated source tarball, I could simply use a simple command to fetch from a static url:

from:

```
PORTNAME=       heimer
DISTVERSION=    3.4.0

USE_GITHUB=     yes
GH_ACCOUNT=     juzzlin
GH_PROJECT=     Heimer

distinfo:
SHA256 (juzzlin-Heimer-3.4.0_GH0.tar.gz) = ###
SIZE (juzzlin-Heimer-3.4.0_GH0.tar.gz) = ###
```
to:

```
PORTNAME=       heimer
DISTVERSION=    3.4.0
MASTER_SITES= https://github.com/juzzlin/Heimer/releases/download/${DISTVERSION}/

distinfo:
SHA256 (heimer-3.4.0.tar.gz) = ###
SIZE (heimer-3.4.0.tar.gz) = ###
```

IMO, all packaging systems that needs fetching and compiling from source will beneficit with this static tarball.

Thanks,

Nuno Eduardo Teixeira
[eduardo@FreeBSD.org](mailto:eduardo@FreeBSD.org)

**Comment by juzzlin** [comment]
Fixed in b8acac9521bb59595e1f908c7f9373264b9f58ed.

From now on I will release also `heimer-x.y.z.tar.gz`.

**Comment by juzzlin** [comment]
https://github.com/juzzlin/Heimer/releases/download/3.4.0/heimer-3.4.0.tar.gz

**Comment by nunotexbsd** [comment]
Thank you!

Cheers
