### ISSUE TITLE
Can a Node have more than one parent

### ISSUE THREAD

**Issue by jmcisvt** [juzzlin/Heimer#221]
I saw a Heimer screenshot where a node has 2 parents. I can't figure out how to do that. Can it be done?

**Comment by juzzlin** [comment]
Not sure if I understood correctly, but you can change the direction of the arrow or remove it completely by right-clicking on an edge (a context menu will be opened).

If this didn't help you then please show me the screenshot :)

**Comment by jmcisvt** [comment]
Ahh, no like a child that has two parent nodes. Two arrows going into it.

https://images.app.goo.gl/SNNqsXaSRKhkHEA8A

**Comment by juzzlin** [comment]
You can 
1) Drag "child" nodes and change the arrow directions.
2) Connect node to another existing node by dragging the connection handle on it. Multiple other nodes can be connected to the same node.

Actually there are no parent and child nodes as any node can be connected to any other node. It's just the default edge arrow that might give you an illusion of a parent and a child.

**Comment by jmcisvt** [comment]
Ok i figured it out. Nice work!
I couldnt find documentation other than the YT video. :)

**Comment by juzzlin** [comment]
Yeah, I need to add documentation of the basic usage. It hasn't been a top priority due to "limited resources", but I think I'll do it soon 😊

**Comment by juzzlin** [comment]
I recently noticed that there's a bug in Heimer 3.6.0 that makes the edge context menu to not open when the edge label is right-clicked :(

Makes it a bit hard to discover.

Already fixed in master branch and a new release coming soon.
