### ISSUE TITLE
Add option to automatically open the last used file on application start

### ISSUE THREAD

**Issue by jamcinnes2** [juzzlin/Heimer#229]
Could you add an option to automatically open the last used file on application start?
Sorry if this is a bad place for feature requests.

**Comment by juzzlin** [comment]
Yes, that would a nice feature. I actually thought about this also myself the other day 😊

**Comment by juzzlin** [comment]
Fixed in 04e4b0c54c34bcfa3bc93394f16eac8df0808b18
