### ISSUE TITLE
Shadow effects introduce performance issues

### ISSUE THREAD

**Issue by juzzlin** [juzzlin/Heimer#238]
There could be an easier way to disable the shadow effects (maybe just a button that sets the shadow parameters to zero) + probably we'd need a border color for the nodes to give some contrast.

**Comment by juzzlin** [comment]
Workaround for this is to go to `File => Settings => Effects` and set `Shadow effect offset` and `Shadow blur radius` to zero.

**Comment by juzzlin** [comment]
This at tries to fix the issue:

03712c8ab49f35469b0a41a9f7bd9ac93d64f4d1

**Comment by elandorr** [comment]
I had already disabled the effects, but that didn't change too much. The issue only arises when zoomed in for some reason. The full map with all the lines over each other is fast.

**Comment by juzzlin** [comment]
Could you please send or attach an example map with the problem so I could try to reproduce?

**Comment by elandorr** [comment]
https://oshi.at/mhgg

Restarting reduced memory consumption <200MB. Not sure the content had anything to do with it, had to clean it. It was mostly a maximum of 2 lines, most just one line, nothing dramatic.

**Comment by l3td33r** [comment]
> I had already disabled the effects, but that didn't change too much. The issue only arises when zoomed in for some reason. The full map with all the lines over each other is fast.

Related to #141 ?

**Comment by elandorr** [comment]
@l3td33r Looks like it. 4.1 with shadows off is definitely an improvement! Thanks for fixing the dragging by the way, that works fine now.
