### ISSUE TITLE
Some enhancements

### ISSUE THREAD

**Issue by CocoCocoAlx** [juzzlin/Heimer#24]
Hi, I've using your amazing app for a while and I like it so much, because it's so faster than other Java-based apps that I try. So, i wan't to make to you some suggestions:

1) make possible to delete the connectors, not the nodes. Of course, I join to the claim of being able to create and reconnect nodes with new connectors;
2) make possible to move several nodes at the same time, by wrapping it with the mouse;
3) make possible to align to center text in the node and change its the color and size of the font.

Many thanks to your work, greetings (and sorry for my bad english)!

**Comment by juzzlin** [comment]
Thank you for your feedback! I'm glad to hear you like Heimer :)

The things you listed are definitely on my backlog. I will create new issues for the things you listed and close this one.
