### ISSUE TITLE
Option to include grid on export

### ISSUE THREAD

**Issue by chromer030** [juzzlin/Heimer#249]
Please add an option in include grid, sometimes nodes are arranged on grids and it's part of the map.

Thanks for great app.

**Comment by juzzlin** [comment]
Are you using PNG or SVG export?

**Comment by chromer030** [comment]
> Are you using PNG or SVG export?

PNG because is more known & common for sharing and sending it to other people.

**Comment by juzzlin** [comment]
Fixed in ff86f23ec5f98e39e687c3c8919886b484e87f58.

Thanks for the suggestion!
