### ISSUE TITLE
2 build errors in Windows

### ISSUE THREAD

**Issue by uicake** [juzzlin/Heimer#259]
(My English is poor)
1. unresolved external symbol
fix: Change all "struct ShadowEffectParams;" to "class ShadowEffectParams;"
2. Heimer and heimer naming conflicts in Windows
fix: 
-set(HEIMER_LIB_NAME ${CMAKE_PROJECT_NAME})
+set(HEIMER_LIB_NAME "${CMAKE_PROJECT_NAME}_static")

Have a nice day! :)

**Comment by juzzlin** [comment]
I guess this is with MS Visual C++ ?

**Comment by juzzlin** [comment]
Fixed in d9e3ac78ace910fced390e6b2697236fb625b263.

Thanks for reporting! :)
