### ISSUE TITLE
Multi-selection for nodes 

### ISSUE THREAD

**Issue by juzzlin** [juzzlin/Heimer#26]
It should be possible to move multiple nodes at once.

**Comment by juzzlin** [comment]
Fixed in master. Ctrl + Left click selects/deselects nodes. Ctrl + Left click on the background clears the selection.

**Comment by joaopauloalbq** [comment]
Hi Jussi,

Ctrl + Left click could also draw a rectangle and select all nodes inside it?

Something like this https://youtu.be/IiQaovjGUJw

**Comment by juzzlin** [comment]
Yeah, should be doable.

**Comment by juzzlin** [comment]
I added a new issue for this: https://github.com/juzzlin/Heimer/issues/58
