### ISSUE TITLE
White text when using dark theme

### ISSUE THREAD

**Issue by joaopauloalbq** [juzzlin/Heimer#31]
White text when using dark theme.

![screenshot_20181015_172259](https://user-images.githubusercontent.com/9905202/46976169-0f4ecc80-d09f-11e8-935f-af042f13483a.png)

**Comment by juzzlin** [comment]
Interesting. Are you able to set the text color black?

**Comment by joaopauloalbq** [comment]
> Interesting. Are you able to set the text color black?
Yes, it's working :)

**Comment by juzzlin** [comment]
I now pushed a fix to `dev` branch. Would it be possible for you to try if that fixes the problem?

**Comment by joaopauloalbq** [comment]
> I now pushed a fix to `dev` branch. Would it be possible for you to try if that fixes the problem?

Sure, my first time building a github project haha.

Bug fixed!! Thank you :]

**Comment by juzzlin** [comment]
Great, thanks for reporting! :)
