### ISSUE TITLE
Add mechanism to set arrow direction

### ISSUE THREAD

**Issue by juzzlin** [juzzlin/Heimer#32]
The user might want to switch the arrow direction or remove the arrow head completely.

**Comment by KarlZeilhofer** [comment]
or an bidirectional arrow with 2 heads

**Comment by kamilizmer** [comment]
> or an bidirectional arrow with 2 heads

Not or but "and" both options is required.

**Comment by juzzlin** [comment]
Workaround for this is to create a floating node and connect it to another node by dragging the (+) handle, which results in a reversed arrow.

**Comment by juzzlin** [comment]
Now properly implemented in d2dd677193954ab147207dbaebba3ac211303c22

Right-click edge shows a context menu with options to set single arrow, double arrow, hide arrows and reverse the direction.
