### ISSUE TITLE
[question] Is text area  using a different toolkit?

### ISSUE THREAD

**Issue by joaopauloalbq** [juzzlin/Heimer#37]
Is text area using a different toolkit? looks like gtk2 for me 

![screenshot_20181213_032257](https://user-images.githubusercontent.com/9905202/49920149-f8064280-fe87-11e8-80e9-6d59a7b2aba9.png)

**Comment by juzzlin** [comment]
The text area is a `QGraphicsTextItem`. I believe it doesn't use any underlying toolkits and looks the same on all platforms.

**Comment by joaopauloalbq** [comment]
Ow, should be an upstream problem

**Comment by juzzlin** [comment]
In your image it looks like it's intended to be, however :)

**Comment by joaopauloalbq** [comment]
Actually, the left context menu has blur. I'm a little perfectionist haha
