### ISSUE TITLE
Add snap to grid option

### ISSUE THREAD

**Issue by joaopauloalbq** [juzzlin/Heimer#39]
To assist on spacing and alignment among nodes.

example:
https://youtu.be/bKS2JSoLYSI

**Comment by juzzlin** [comment]
Nice video :) I'll do this for the next release. At least an "invisible" grid.

**Comment by joaopauloalbq** [comment]
Thanks. "invisible" grid is sufficient xD

**Comment by joaopauloalbq** [comment]
I believe the grid setting should be a global setting (enabled by default haha) because the user will like it or not, so they will set this option only once, not per map.

**Comment by juzzlin** [comment]
There is now a simple grid size setting in the toolbar. If the size is 0 nothing happens. If the size is > 0 it snaps. I liked that. Thanks for suggesting this!

**Comment by joaopauloalbq** [comment]
I'm happy to help. I builded from dev, it's perfect!
