### ISSUE TITLE
Cannot install macOS High Seirra

### ISSUE THREAD

**Issue by sitthykun** [juzzlin/Heimer#43]
I did
$ chmod a+x Heimer-1.6.0-x86_64.AppImage
zsh: exec format error: ./Heimer-1.6.0-x86_64.AppImage

**Comment by juzzlin** [comment]
Hi,

AppImage is generic packaging format for Linux. Unfortunately there are no packages for macOS currently as I don't have a Mac. However, you should still be able to build the application from sources for Mac.

**Comment by HeathNaylor** [comment]
For the record, I was able to get this to work on OSX (macOS). I installed `qt5` via brew and then I had to find the qt5 cmake directory and link it to `CMAKE_PREFIX_PATH`:

```
sudo find / -name Qt5Core
```

From here I took the path provided and updated my `CMAKE_PATH_PREFIX`:

```
export CMAKE_PREFIX_PATH=/usr/local/Cellar/qt/5.15.0/lib/cmake:$CMAKE_PREFIX_PATH
```

After that was done I followed the directions [here](https://github.com/juzzlin/Heimer#building-the-project). Once installed, I had a file called `heimer` that I could execute through the cli:
```
./heimer
```

**Comment by juzzlin** [comment]
That's right, one should be able to build and run on OS X without any problems. I just don't use OS X myself so never tested that.
