### ISSUE TITLE
How To translate Heimer ?

### ISSUE THREAD

**Issue by olielvewen** [juzzlin/Heimer#44]
Hi,
I've discovered Heimer since a little time and I've played a bit with. I like it.

I would like to translate it in French. Could you give me some explanations about this ? 

Thanks a lot.

**Comment by juzzlin** [comment]
Hi, please check `Adding/updating translations` in `CONTRIBUTING`.

**Comment by olielvewen** [comment]
I've translated today in French.

Really nice your script. 

My main issue is to test it with the local french like I'm using it with an appimage. 

Heimer is not yet available/packaged on AUR neither on AMAR (another manjaro repository) even I've asked for this repo (i.e amar) there are a while but without any success.

BTW: My system is a Manjaro Cinnamon. 

I'm able to run it with QtCreator but strangely I can't see the french file in the tree file.

I would like to modified a translation that I've done but I've not been able to re-run this nice script.
Permission denied.
How can I do that ? Did you have an idea ? Manually ? How ?

**Comment by juzzlin** [comment]
You need to add the new .qm-file to data/translations/translations.qrc:

```
<RCC>
    <qresource prefix="/">
        <file>heimer_fi.qm</file>
        <file>heimer_fr.qm</file>
    </qresource>
</RCC>
```

After this it will be shown in the tree view in QtCreator. Now when you build the app it should be in French if your operating system is in French.

If you want to manually force the language you must give `--lang fr` to Heimer. In QtCreator you can set the CLI arguments. However, in my opinion this is easier if you build in the command line:

```
$ mkdir build
$ cd build
$ cmake ..
$ make -j4
$ ./heimer --lang fr
```

You cannot use the existing packages for testing unless you build your own AppImage or some other package (there's scripts/buildAppImage.sh, but it requires Docker). 

If you end up making a pull request, there should be at least these three things:
- A new file `src/translations/heimer_fr.ts`
- A new file `data/translations/heimer_fr.qm`
- The changes to `data/translations/translations.qrc`

**Comment by juzzlin** [comment]
Which script gave you that "Permission denied." ?

**Comment by olielvewen** [comment]
This one : 
`[olivier@luthien Heimer]$ ./scripts/updateTranslationFiles.sh fr`
Yesterday, impossible.

Today, call the last command in my terminal and all run fine. Sometimes, you should not  understand why . Well the most important is that works. 

I've updated all french translations and done one modification. In the mainwindow file, you should modified the &About string and then added the name of the project ie Heimer. Like you have done for the About dialog/screen (i.e Heimer is added automatically.

**Comment by juzzlin** [comment]
I added an option to set the edge color. Two new strings: one is in the edit menu and one in the right-click context menu.

**Comment by olielvewen** [comment]
Hi,
Here a patch for the new French Translation. Sorry for the delay, I've had the flue....
I hope that this patch is good. Tell me if all is okay. Have a great week-end with the beautiful forecast.

diff --git a/data/translations/heimer_fr.qm b/data/translations/heimer_fr.qm
index b2ab55b..7f1daea 100644
Binary files a/data/translations/heimer_fr.qm and b/data/translations/heimer_fr.qm differ
diff --git a/src/translations/heimer_fr.qm b/src/translations/heimer_fr.qm
new file mode 100644
index 0000000..7f1daea
Binary files /dev/null and b/src/translations/heimer_fr.qm differ
diff --git a/src/translations/heimer_fr.ts b/src/translations/heimer_fr.ts
index f9fd664..f338d31 100644
--- a/src/translations/heimer_fr.ts
+++ b/src/translations/heimer_fr.ts
@@ -72,7 +72,7 @@
     <message>
         <location filename="../editor_view.cpp" line="68"/>
         <source>Set edge color</source>
-        <translation type="unfinished"></translation>
+        <translation>Affichage de la couleur du bord</translation>
     </message>
     <message>
         <location filename="../editor_view.cpp" line="76"/>
@@ -120,7 +120,7 @@
     <message>
         <location filename="../main_window.cpp" line="110"/>
         <source>Set edge color</source>
-        <translation type="unfinished"></translation>
+        <translation>Affichage de la couleur du bord</translation>
     </message>
     <message>
         <location filename="../main_window.cpp" line="133"/>

**Comment by juzzlin** [comment]
Ok, no problem! Thanks! :)
