### ISSUE TITLE
Allow Grouping/Ungrouping of nodes

### ISSUE THREAD

**Issue by ProfElectric** [juzzlin/Heimer#48]
Allow nodes to be grouped so that if one node in the group is selected, they are all selected; if one is moved, the all move together.

In addition to that mentioned in issue #26, the grouping should persist between sessions.

**Comment by juzzlin** [comment]
I'm not sure I agree on the persistence yet, but the grouping itself is something I'm planning to work on soon.

**Comment by juzzlin** [comment]
Grouping with Ctrl + Left click is now fixed in master branch.

**Comment by mlovizio** [comment]
## Group persistence option
### *Is still under consideration the option for persisting grouping?*

Group actions as they are implemented at the time of my comment, are excellent but you are 1 misclick away of needing to select one by one all the nodes.

I found really useful converting the selected entities into groups (persistent but with possibility ungrouping or toggle off/on the group actions) while I work in CAD programs.
