### ISSUE TITLE
Snap to grid

### ISSUE THREAD

**Issue by ProfElectric** [juzzlin/Heimer#49]
Grid properties should be changeable in the GUI, and Snap to Grid should be an option

**Comment by juzzlin** [comment]
What is the difference to the current implementation where you can set the grid size in the toolbar?

**Comment by ProfElectric** [comment]
Hmmm...I don't see that in mine.

**Comment by juzzlin** [comment]
This was implemented in 1.6.0.

**Comment by juzzlin** [comment]
![grid_size](https://user-images.githubusercontent.com/2587783/52665138-82fccb00-2f13-11e9-85c3-1d660a2080e3.png)

**Comment by ProfElectric** [comment]
Oh...I... *face palm*

**Comment by juzzlin** [comment]
No worries! :)
