### ISSUE TITLE
Autoarrange Nodes

### ISSUE THREAD

**Issue by ProfElectric** [juzzlin/Heimer#50]
Finally, a thought/mind/process mapping tool that is really easy to use and doesn't use Java!  Thank you! 

A feature to auto-arrange nodes would be amazing.  I'm working with a new school utilizing heavy automation and my current project has been greatly augmented by this too.  
I'm working on a map right now which shows the relationships of services and resources offered by our infrastructure and the OpenStack services that make them possible.  I've only just begun and this thing is getting pretty hairy.

**Comment by juzzlin** [comment]
You're welcome :)

I've been thinking of something like that. Any suggestions on how that would work?

**Comment by stakaz** [comment]
Hey, I cannot tell you how the things are done there, but as an idea of possible methods you could look at [yed](https://www.yworks.com/products/yed). They really have nice features for this option which are missing in all other software I have seen so far.

**Comment by juzzlin** [comment]
I wrote a prototype method of auto arrange some time ago, but couldn't decide if that was cool or crap :) Maybe I'll look into that again when I have time. At least that branch should be rebased on the current master.

**Comment by juzzlin** [comment]
I have been working on this for a pretty long time and now I think the first version is finally somewhat useful. Implemented in dcac559fb6d79a91eb4d0738f513e4e86f7fa800.
