### ISSUE TITLE
Insert Images Into Nodes

### ISSUE THREAD

**Issue by ProfElectric** [juzzlin/Heimer#51]
I think it'd be really great to insert images (maybe as a faded background element which auto-scales to the node size) so that those nodes will stand out more.  With maps like the one I'm currently working on which have over 50 nodes (and growing), an image could make the map easier to navigate.  

This is especially the case if auto-arranging of nodes becomes and option.

I realize this would probably require a new file format, but tar-gzipping the contents similar to what LibreOffice (and others) do should be sufficient, I would think.

**Comment by juzzlin** [comment]
The original idea was to be able to embed all kinds of attachment data like images in the current file format. So I guess this is doable :)

**Comment by juzzlin** [comment]
Implemented in c4e9e00e0e27a3430ac3a593f75987813ea788ea.

**Comment by mmahmoudian** [comment]
@juzzlin I just installed this tool and I was hoping to be able to add images to the nodes but copy-pasting does not work, right-click menu or the application menu do not have any option for importing (either from clipboard or file). Searching through the issues of the repo got me to this thread which you stated in 2019 that it is implemented. Would you please guide me on how to do this?

P.s: the snap gave me segfault:

> ```
> ❯  snap run heimer
> WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
> Mon Sep 27 14:44:50 2021 [I] Heimer version 2.6.0
> Mon Sep 27 14:44:50 2021 [I] Copyright (c) 2018-2021 Jussi Lind
> Mon Sep 27 14:44:50 2021 [I] Compiled against Qt version 5.9.5
> Mon Sep 27 14:44:50 2021 [I] Trying Qt translations for 'en-US'
> Mon Sep 27 14:44:50 2021 [W] Failed to load Qt translations for 'en-US'
> Mon Sep 27 14:44:50 2021 [I] Trying application translations for 'en-US'
> Mon Sep 27 14:44:50 2021 [W] Failed to load application translations for 'en-US'
> Fontconfig warning: FcPattern object weight does not accept value [40 210)
> [1]    16428 segmentation fault (core dumped)  snap run heimer
> ```

So I'm Running the AppImage (which I also personally prefer).

**Comment by juzzlin** [comment]
Unfortunately the only way to add an image currently is to select a file. Not sure about that snap issue - it works on my Ubuntu 20.04 just fine.

**Comment by juzzlin** [comment]
I didn't see `Fontconfig warning: FcPattern object weight does not accept value [40 210)` on my setup so maybe that's related to the crash.
