### ISSUE TITLE
Adding to AUR

### ISSUE THREAD

**Issue by tiotrom** [juzzlin/Heimer#52]
I was wondering if there is any plan to add it to AUR. Thank you!

**Comment by juzzlin** [comment]
Not from my side as there are already too many different packages :) Someone else is of course free to create packaging for Arch.

**Comment by tiotrom** [comment]
We did it - https://aur.archlinux.org/packages/heimer-git/

**Comment by tiotrom** [comment]
Hey guys. We are unable to support the AUR version of this package. Are you able to help with that? https://aur.archlinux.org/packages/heimer-git/ Let us know, if you can't we will strive to maintain it but we can't promise. Cheers!

**Comment by juzzlin** [comment]
Well, I'm also too busy :)

**Comment by tiotrom** [comment]
I understand. We will try to keep it updated ;)
