### ISSUE TITLE
Scalable cards

### ISSUE THREAD

**Issue by r4nd3l** [juzzlin/Heimer#63]
Chance to scale the horizontal size of the cards, to make a nicer look when you paste in texts.

**Comment by juzzlin** [comment]
There's a task about adding option for double-wide nodes, but I guess they could be also scalable. Need to test this a bit :)

**Comment by r4nd3l** [comment]
Sounds good! Good to hear my prayers have been listened to! :D

**Comment by juzzlin** [comment]
I implemented automatic scaling of width in a41b8f5601ff8e5b072fad4b3cda1c8949f99de5. Seems to work flawlessly, but might need a bit more testing before releasing.

**Comment by r4nd3l** [comment]
I'll take a look at it
