### ISSUE TITLE
segmentation fault on Debian 10 Buster

### ISSUE THREAD

**Issue by paulcobbaut** [juzzlin/Heimer#65]
Hello,

Thank you for this wonderful tool.

I created a fairly large (edge to edge) mind map with Heimer 1.10 on Debian. This worked without a problem. When editing the mind map (inserting text in an existing node) I regularly get a segmentation fault. Upgrading to 1.11 same result.

I compiled the latest Heimer from source, but again same segmentation fault. Often editing nodes works flawlessly, but regularly it faults (crash to desktop).

strace gives this output:

paul@MBDebian~/lt4/git$ strace -o heimer.strace heimer lt4mindmap.alz                        
[Mon Oct 14 14:20:18 2019] I: Heimer version 1.11.0                                          
[Mon Oct 14 14:20:18 2019] I: Copyright (c) 2018 Jussi Lind                                  
[Mon Oct 14 14:20:18 2019] I: Compiled against Qt version 5.11.3                             
[Mon Oct 14 14:20:18 2019] W: Failed to load Qt translations for en_US                       
[Mon Oct 14 14:20:18 2019] W: Failed to load application translations for en_US              
Segmentation fault
paul@MBDebian~/lt4/git$

The strace file itself is 18000 lines, would this be useful to you ?

greetings,
paul

**Comment by juzzlin** [comment]
GDB stack of a debug build would be useful and also the actual `lt4mindmap.alz` for testing, if possible :)

**Comment by juzzlin** [comment]
You can build debug build by giving `-DCMAKE_BUILD_TYPE=Debug` to CMake.

**Comment by paulcobbaut** [comment]
Compiled the latest with Debug, strace now gives more information.

Can you give me the gdb command please (I am not a developer). I will reply later tonight and will send you the mind map by mail (please keep it private).

paul@MBDebian~/lt4/git$ strace -o heimer.strace heimer lt4mindmap.alz                         
[Mon Oct 14 16:02:33 2019] I: Heimer version 1.11.0                                           
[Mon Oct 14 16:02:33 2019] I: Copyright (c) 2018 Jussi Lind                                   
[Mon Oct 14 16:02:33 2019] I: Compiled against Qt version 5.11.3                              
[Mon Oct 14 16:02:33 2019] W: Failed to load Qt translations for en_US                        
[Mon Oct 14 16:02:33 2019] W: Failed to load application translations for en_US               
[Mon Oct 14 16:02:33 2019] D: Initializing a new mind map                                     
[Mon Oct 14 16:02:33 2019] D: Initializing view                                               
[Mon Oct 14 16:02:33 2019] D: Dummy drag item reset                                           
[Mon Oct 14 16:02:33 2019] D: Added existing node 0 to scene                                  
[Mon Oct 14 16:02:33 2019] D: Initializing view                                               
[Mon Oct 14 16:02:33 2019] D: Dummy drag item reset                                           
[Mon Oct 14 16:02:33 2019] D: Opening 'lt4mindmap.alz                                         
[Mon Oct 14 16:02:33 2019] D: Graph deleted                                                   
[Mon Oct 14 16:02:33 2019] D: Initializing view                                               
[Mon Oct 14 16:02:33 2019] D: Dummy drag item reset                                           
[Mon Oct 14 16:02:33 2019] D: Added existing node 0 to scene                                  
[Mon Oct 14 16:02:33 2019] D: Added existing node 1 to scene                                  
[Mon Oct 14 16:02:33 2019] D: Added existing node 2 to scene 
...output truncated...
[Mon Oct 14 16:02:33 2019] D: Added existing edge 145 -> 152 to scene                        
[Mon Oct 14 16:02:33 2019] D: Added existing edge 148 -> 151 to scene                        
[Mon Oct 14 16:02:50 2019] D: Saving undo point..                                            
[Mon Oct 14 16:02:53 2019] D: Saving undo point..                                            
Segmentation fault

**Comment by juzzlin** [comment]
Ok, in terminal:

```
$ gdb heimer
(gdb) run

... and when it crashes ...

(gdb) bt

```

I would still very much like to be able to reproduce this also myself.

**Comment by paulcobbaut** [comment]
This is the gdb output. The program hanged now instead of crash to Desktop.

[gdb.output.txt](https://github.com/juzzlin/Heimer/files/3725185/gdb.output.txt)

**Comment by juzzlin** [comment]
According to the back trace it seems to crash somewhere deep inside Qt so it might not be a Heimer problem after all. So far I haven't been able to reproduce this. I have tried to do the copy-paste multiple times. Then again my dev Heimer is now compiled against Qt 5.12.2.

**Comment by paulcobbaut** [comment]
It works in wine! So problem solved for me.

(I had no luck with Debian-Experimental and qt5.12.5 in a vm.)
