### ISSUE TITLE
Add fullscreen option

### ISSUE THREAD

**Issue by joaopauloalbq** [juzzlin/Heimer#66]

**Comment by juzzlin** [comment]
Thanks for suggestion! Implemented in c4e9e00e0e27a3430ac3a593f75987813ea788ea. There's now View => Full Screen that can be toggled.

**Comment by joaopauloalbq** [comment]
Jussi always being awesome!

**Comment by joaopauloalbq** [comment]
Hi @juzzlin , 

There is no way to get out of full screen, 
how about ESC to get out of full screen? 
A shortcut would also be of interest to get in and out of full screen, like F11.

Happy New Year

**Comment by juzzlin** [comment]
Just click again "Full Screen" ;)

It was done like this in Qt Creator IDE. I got the idea from there.

**Comment by juzzlin** [comment]
However, I think this could be made clearer and even use ESC like you suggested.
