### ISSUE TITLE
Button to drag cards

### ISSUE THREAD

**Issue by tiotrom** [juzzlin/Heimer#67]
So many times I am having difficulties dragging and repositioning cards. I either click the node button and I create a new card in the process, or I click the other buttons. Look at this card that has a bit more text, only the very thin white lines can be clicked to drag and is very difficult:
![2019-11-19_16-58](https://user-images.githubusercontent.com/34804533/69163069-e5f83f80-0aed-11ea-9f35-492e97f64a70.png)
Maybe either add a drag button like you did for the other ones, or make the borders a lot bigger, or simply allow to click the text area and drag the card like that. And only when double click the text area to edit the text.

Cheers!

**Comment by juzzlin** [comment]
Yeah, this is a bit clumsy. A good suggestion!

**Comment by juzzlin** [comment]
I had some extra motivation to implement right away. Fixed in 4dda79f760d9c31c828ba249bd4ca7191baf7cab

**Comment by tiotrom** [comment]
Oh awesome! Waiting for the new release!
