### ISSUE TITLE
Edge tries to reposition while moving a group

### ISSUE THREAD

**Issue by juzzlin** [juzzlin/Heimer#70]
Attached an example of a layout that reveals the issue when selecting all and moving the group around.

[MoveBug.alz.gz](https://github.com/juzzlin/Heimer/files/3907432/MoveBug.alz.gz)

**Comment by KarlZeilhofer** [comment]
I was looking for that feature to select multiple nodes, but it didn't work with an expected rubber band select. How can I select multiple nodes?

**Comment by juzzlin** [comment]
Rubber band selection works if Ctrl is being pressed. You can select multiple nodes also with Ctrl+Click.

**Comment by juzzlin** [comment]
Fixed in 142aedca4ab88ef1138830136b86b4db84702255
