### ISSUE TITLE
Export SVG

### ISSUE THREAD

**Issue by KarlZeilhofer** [juzzlin/Heimer#85]
Hi, 
it would be great, if the application could also export into SVG for proper printing and tweaking. Isn't this supported very easily with the Qt SDK?
greets, Karl

**Comment by juzzlin** [comment]
After some googling seems to doable at least in theory :)

**Comment by juzzlin** [comment]
I tried to do this, but for some reason all nodes are just bitmapped in the SVG file and it looks very bad. I wouldn't like to manually construct the SVG data :)

**Comment by juzzlin** [comment]
It seems that it's the drop shadow effect that forces everything to bitmaps.

**Comment by juzzlin** [comment]
Implemented in 6600d2a59d462ca2660f1e14f2d18443f46679d7

**Comment by KarlZeilhofer** [comment]
Awesome! Thanks!

**Comment by KarlZeilhofer** [comment]
@juzzlin I just tried it now the first time, and it works great!
A minor improvement could be the grouping of the elements, that a node represents a SVG-group. 
Currently the whole drawing is a group. After exploding it, all elements are separated.

**Comment by juzzlin** [comment]
It's using `QSvgGenerator` so I'm not sure if that kind of things are possible. Need to investigate :) Thanks for the feedback!
