### ISSUE TITLE
Default Right-to-Left Text

### ISSUE THREAD

**Issue by rwaguy** [juzzlin/Heimer#89]
Compiled fine (directly from GitHub), but when there are these errors:

[I] Loaded Qt translations for en_US
[W] Failed to load application translations for en_US
qt5ct: D-Bus global menu: no

The default text becomes Right-to-Left.  I realize this is likely a setup error on my system (Manjaro/Arch), but since it's the default setup, it may affect more than my distribution, so I thought that I should mention it.

![heimer-text-problem_2020-05-11_06-15-23](https://user-images.githubusercontent.com/4008601/81550902-ebbd3800-934e-11ea-99d6-9a7034a8f771.png)

**Comment by juzzlin** [comment]
That's indeed a bit strange. What does `locale` output on your system?

**Comment by cabelo** [comment]
in my system to... my locate is Portuguese.

**Comment by juzzlin** [comment]
This seems to happen also on Ubuntu 20.04 with Qt 5.12.5. Something has changed in Qt, I guess.

**Comment by juzzlin** [comment]
Actually...this seems to be a side-effect of the bug fix in e8192b4218dd374139a4fe4eecb5d7b8a9ead959. Older versions work correctly. I'll try to figure out a way to fix this.

**Comment by juzzlin** [comment]
Fixed in 2bc33fa423251757507628f4bdeffbab0c407bd1.

Thank you for reporting this!
