### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by TeLLie** [juzzlin/Heimer#92]
Hi,
When i tried to compile i see that a file is missing.
Heimer/src/unit_tests/serializer_test/serializer_test.cpp:19:10: fatal error: node_base.hpp: No such file or directory
Any idea where to find this file?

**Comment by juzzlin** [comment]
`node_base.hpp` is not used anymore anywhere and it doesn't exist so I believe you have some outdated files these. Try to clean your build dir, update the codes and try again.

I guarantee that the current master builds just fine.
