### ISSUE TITLE
no appimage for 1.17.0?

### ISSUE THREAD

**Issue by tiotrom** [juzzlin/Heimer#93]
![image](https://user-images.githubusercontent.com/34804533/84963918-097a7b80-b10b-11ea-9c2e-b793006360c1.png)

**Comment by juzzlin** [comment]
There was an issue with a missing symbol due to `qt_qhash_seed` being removed, but now I realized that maybe it was just a mishap with `ccache`. 

I uploaded AppImage now, thanks!
