### ISSUE TITLE
Redo does stuff when redo shouldn't be possible

### ISSUE THREAD

**Issue by ReFreezed** [juzzlin/Heimer#97]
Version: 1.18.0
OS: Windows 7, 64-bit

Step to reproduce:
- Open new document.
- Make a change.
- Undo.
- Make another change.
- It's now somehow possible to redo.

It seems the undone history isn't cleared when making new changes.

**Comment by juzzlin** [comment]
Confirmed.

**Comment by juzzlin** [comment]
A bit trickier to fix than I expected. Fixed in bbc59408e8c40b37a0258bb4db7b472abfe88091. Thanks for reporting!
